import { create } from 'zustand';

export interface Article {
  id: string;
  headline: string;
  subheadline?: string;
  dateline: string;
  byline: string;
  body: string;
  image?: string;
  caption?: string;
  category: string;
  columnSpan?: number;
}

interface ContentState {
  articles: Article[];
  getArticlesByCategory: (category: string) => Article[];
  getArticleById: (id: string) => Article | undefined;
}

const articles: Article[] = [
  // === FRONT PAGE (5) ===
  {
    id: 'fp-1',
    headline: 'TERRIBLE COLLIERY EXPLOSION IN YORKSHIRE',
    subheadline: 'Seventy-Five Miners Perish in the Darkest Pit Disaster in a Generation',
    dateline: 'From our Special Correspondent, Trimdon Grange, June 14',
    byline: 'THOMAS BLACKWOOD',
    body: 'The mining village of Trimdon Grange was plunged into unspeakable grief yesterday when a tremendous explosion ripped through the coal workings of the North-Eastern Colliery Company. The blast, which occurred shortly after half-past two in the afternoon, was heard for miles across the Durham countryside, sending a column of black smoke and debris shooting from the pithead.\n\nRescue parties were immediately organised by the mine superintendent Mr. Henry Chaytor, and volunteers from neighbouring collieries rushed to the scene. By nightfall, fifty-eight bodies had been recovered from the deep workings, with a further seventeen men still unaccounted for. The survivors, many of whom suffered dreadful burns and crush injuries, were conveyed to the Durham Infirmary.\n\nPreliminary investigations suggest that a accumulation of firedamp in the Hutton Seam was ignited by a defective safety lamp. The North-Eastern Colliery Company has announced a full inquiry, whilst the coroner has opened an inquest. The Prime Minister, the Marquess of Salisbury, has expressed his profound sympathy for the bereaved families.',
    category: 'front',
    columnSpan: 3,
  },
  {
    id: 'fp-2',
    headline: 'Royal Visit to Manchester Cancelled',
    subheadline: 'Her Majesty indisposed — the Prince of Wales to attend in her stead',
    dateline: 'From our Court Correspondent, Buckingham Palace, June 14',
    byline: 'By Our Court Reporter',
    body: 'It is with much regret that we announce the cancellation of Her Majesty the Queen\'s proposed visit to Manchester and Salford, which had been arranged for the twenty-second instant. Royal physicians have advised Her Majesty to postpone all public engagements for the remainder of the month owing to a slight indisposition.\n\nHis Royal Highness the Prince of Wales has graciously consented to represent Her Majesty at the opening of the new Royal Infirmary. The Princess of Wales will accompany His Royal Highness.',
    category: 'front',
    columnSpan: 1,
  },
  {
    id: 'fp-3',
    headline: 'New Railway Line to Scotland Opens',
    subheadline: 'The Great North Express now reaches Edinburgh in under eight hours',
    dateline: 'From our Special Correspondent, York, June 13',
    byline: 'By Our Railway Correspondent',
    body: 'The North British Railway Company yesterday inaugurated its new direct line to Edinburgh, cutting the journey time from London to the Scottish capital to a remarkable seven hours and fifty-two minutes. The first train, hauled by the new Class C locomotive, departed King\'s Cross at seven in the morning and arrived at Waverley Station to a tremendous reception.\n\nThe new line includes the spectacular Royal Border Bridge at Berwick-upon-Tweed, an engineering marvel of twenty-eight arches spanning the River Tweed. Sir Thomas Bouch, the engineer responsible, was present to receive the congratulations of the railway directors.',
    image: 'hero-engraving-front.jpg',
    caption: 'The new terminus at Waverley, Edinburgh — a scene of great celebration',
    category: 'front',
    columnSpan: 1,
  },
  {
    id: 'fp-4',
    headline: 'French Exposition Draws Record Crowds',
    subheadline: 'Over fifty thousand visitors daily at the Paris Universal Exhibition',
    dateline: 'From our Special Correspondent, Paris, June 13',
    byline: 'By Our Foreign Staff',
    body: 'The Paris Universal Exhibition of 1901 continues to attract extraordinary numbers of visitors from all corners of the globe. The Grand Palais, that magnificent structure of iron and glass on the Champ de Mars, has become the centre of international attention as nations display their finest industrial, artistic, and scientific achievements.\n\nThe British Pavilion, under the direction of Sir Isidore Spielmann, has drawn particular praise for its comprehensive display of colonial goods and manufactured articles. The Indian Court, with its priceless collection of jewels and brocades, remains the most visited section of the entire exhibition.',
    category: 'front',
    columnSpan: 1,
  },
  {
    id: 'fp-5',
    headline: 'Distress in the Cotton Trade',
    subheadline: 'Mills in Lancashire announce further reductions in working hours',
    dateline: 'From our Correspondent, Manchester, June 14',
    byline: 'By Our Commercial Reporter',
    body: 'The depressed state of the cotton trade shows no sign of improvement, with a further fifteen mills in the Oldham district announcing reductions in working hours from Monday next. Some seven thousand operatives will be affected by the new arrangements, which reduce the working week from fifty-five to forty-eight hours.\n\nThe Manchester Chamber of Commerce has petitioned the Government for relief, citing unfair competition from Indian and Japanese mills. The President, Mr. Edward P. Thompson, described the situation as the most serious in living memory.',
    category: 'front',
    columnSpan: 1,
  },
  // === FOREIGN AFFAIRS (5) ===
  {
    id: 'fa-1',
    headline: 'Franco-Russian Alliance Strengthened',
    subheadline: 'New military convention signed at the Quai d\'Orsay',
    dateline: 'From our Special Correspondent, Paris, June 12',
    byline: 'By Our Foreign Editor',
    body: 'The Entente Cordiale between France and the Russian Empire was further cemented yesterday with the signature of a new military convention at the French Ministry of Foreign Affairs. M. Delcassé, the French Foreign Minister, and Count Nelidoff, the Russian Ambassador, affixed their signatures to the document in a ceremony of the utmost solemnity.\n\nThe new agreement provides for mutual military assistance in the event of aggression by any third power, and establishes a permanent joint staff commission to coordinate strategic planning. The German press has reacted with predictable alarm to this latest development in European power politics.',
    image: 'engraving-foreign-01.jpg',
    caption: 'The diplomatic reception at the Quai d\'Orsay following the signing',
    category: 'foreign',
    columnSpan: 2,
  },
  {
    id: 'fa-2',
    headline: 'Boxer Rebellion: Allied Forces Advance',
    subheadline: 'Relief expedition prepares to march on Peking',
    dateline: 'From our Correspondent with the Forces, Tientsin, June 10',
    byline: 'By Our War Correspondent',
    body: 'The allied expeditionary force, comprising British, French, Russian, American, and Japanese troops, has established its headquarters at Tientsin and is preparing for the overland march to Peking. The foreign legations in the Chinese capital have now been besieged for twenty-three days, and the situation of the defenders grows daily more critical.\n\nGeneral Sir Alfred Gaselee, commanding the British contingent, has expressed confidence that the legations can be relieved within a fortnight. Some eight thousand troops are assembled at Tientsin, with heavy artillery and ample supplies.',
    category: 'foreign',
    columnSpan: 1,
  },
  {
    id: 'fa-3',
    headline: 'Turkish Massacres in Armenia Condemned',
    subheadline: 'British Government demands investigation of atrocities',
    dateline: 'From our Correspondent, Constantinople, June 11',
    byline: 'By Our Special Correspondent',
    body: 'Fresh reports of atrocities against the Armenian Christian population in the eastern provinces of the Ottoman Empire have reached Constantinople, prompting a strongly worded protest from the British Ambassador, Sir Nicholas O\'Conor. It is estimated that several thousand Armenians have been killed in the Vilayet of Diyarbakir alone.\n\nThe Sultan\'s Government has denied all responsibility, blaming the disturbances on Kurdish brigands. However, European consuls in the region report that Ottoman regular troops participated in the massacres. Lord Salisbury has indicated that Britain may press for international action.',
    category: 'foreign',
    columnSpan: 1,
  },
  {
    id: 'fa-4',
    headline: 'Venezuela Border Dispute Escalates',
    subheadline: 'British Guiana boundary commission suspended',
    dateline: 'From our Correspondent, Georgetown, June 9',
    byline: 'By Our Colonial Correspondent',
    body: 'The Anglo-Venezuelan boundary commission, established to determine the disputed frontier between British Guiana and the Republic of Venezuela, has suspended its sittings following renewed clashes between British troops and Venezuelan irregulars.\n\nThe Venezuelan Government continues to assert claims to territory extending east of the Schomburgk Line, despite the unanimous finding of the international arbitral tribunal of 1899. The Colonial Office has despatched HMS Retribution to the coast as a precautionary measure.',
    image: 'engraving-foreign-02.jpg',
    caption: 'The disputed territory on the Orinoco River',
    category: 'foreign',
    columnSpan: 1,
  },
  {
    id: 'fa-5',
    headline: 'German Naval Expansion Alarms Admiralty',
    subheadline: 'New battleship programme threatens British supremacy at sea',
    dateline: 'From our Naval Correspondent, Whitehall, June 13',
    byline: 'By Our Naval Expert',
    body: 'Confidential memoranda prepared by the Director of Naval Intelligence, Captain Reginald Custance, have caused considerable alarm in Government circles. The documents reveal that the German Imperial Navy has embarked upon an ambitious programme of battleship construction that will double the size of the High Seas Fleet within five years.\n\nThe First Lord of the Admiralty, Lord Selborne, is understood to be pressing the Cabinet for increased naval estimates to maintain Britain\'s two-power standard. The German Ambassador, Count von Hatzfeldt, has been received at the Foreign Office for an explanation.',
    category: 'foreign',
    columnSpan: 1,
  },
  // === DOMESTIC NEWS (5) ===
  {
    id: 'dn-1',
    headline: 'Parliament Debates Workmen\'s Compensation',
    subheadline: 'Mr. Chamberlain proposes sweeping reforms for industrial injuries',
    dateline: 'From our Parliamentary Reporter, Westminster, June 14',
    byline: 'By Our Parliamentary Reporter',
    body: 'The House of Commons last night debated the Second Reading of Mr. Joseph Chamberlain\'s Workmen\'s Compensation Bill in a session of unusual passion and duration. The Colonial Secretary, who has made this measure his personal crusade, delivered a powerful speech of two hours, citing the terrible human cost of industrial accidents.\n\nThe Bill proposes that employers be made strictly liable for all injuries sustained by workmen in the course of their employment, regardless of fault. The Opposition, led by Sir Henry Campbell-Bannerman, has indicated support, though the railway companies and mine owners have lobbied fiercely against the measure.',
    image: 'engraving-domestic-01.jpg',
    caption: 'The House of Commons during last night\'s debate',
    category: 'domestic',
    columnSpan: 2,
  },
  {
    id: 'dn-2',
    headline: 'London\'s New Underground Railway Opened',
    subheadline: 'Central London Railway connects Shepherd\'s Bush to the Bank',
    dateline: 'From our Correspondent, London, June 12',
    byline: 'By Our London Editor',
    body: 'The Central London Railway, known colloquially as the "Twopenny Tube," was formally opened by the Prince of Wales yesterday, to the immense satisfaction of the travelling public. The new line runs from Shepherd\'s Bush in the west to the Bank of England in the City, with thirteen stations along its nine-mile route.\n\nThe trains, hauled by American-built electric locomotives, are capable of speeds hitherto unimagined in underground travel. The carriages are spacious, brilliantly lit by electric light, and remarkably free from the smoke and sulphurous fumes that have made the older underground lines so objectionable.',
    category: 'domestic',
    columnSpan: 1,
  },
  {
    id: 'dn-3',
    headline: 'Birmingham Chamber of Commerce Reports Prosperity',
    subheadline: 'Manufacturing orders at highest level since the Jubilee',
    dateline: 'From our Correspondent, Birmingham, June 11',
    byline: 'By Our Commercial Staff',
    body: 'The quarterly report of the Birmingham Chamber of Commerce presents a picture of unqualified prosperity in the Midlands manufacturing district. Export orders for metal goods, guns, and jewellery have reached their highest level since the Diamond Jubilee, and the number of operatives in employment has increased by twelve per cent over the previous quarter.\n\nMr. Arthur Chamberlain, the President, attributed this success to the aggressive pursuit of colonial markets and the excellence of British workmanship. New factory construction is proceeding at an unprecedented pace in the Aston and Small Heath districts.',
    category: 'domestic',
    columnSpan: 1,
  },
  {
    id: 'dn-4',
    headline: 'Welsh Nationalists Demand Disestablishment',
    subheadline: 'Great meeting at Caernarfon calls for separation of Church and State',
    dateline: 'From our Correspondent, Caernarfon, June 10',
    byline: 'By Our Welsh Correspondent',
    body: 'An immense concourse of Welshmen assembled on the historic Castle Green at Caernarfon to demand the disestablishment of the Church of England in Wales. Mr. Lloyd George, the Member for Carnarvon Boroughs, delivered a speech of extraordinary eloquence, denouncing the Anglican Church as an alien institution imposed upon the Welsh nation.\n\nResolutions were passed calling upon the Liberal Party to make Welsh disestablishment a plank in its next election platform. Mr. Herbert Lewis, Member for Flintshire, presented a petition bearing twenty thousand signatures.',
    image: 'engraving-domestic-02.jpg',
    caption: 'The scene on Castle Green, Caernarfon',
    category: 'domestic',
    columnSpan: 1,
  },
  {
    id: 'dn-5',
    headline: 'Salvation Army Opens New Barracks in Whitechapel',
    subheadline: 'General Booth attends dedication of largest East End mission',
    dateline: 'From our Correspondent, Whitechapel, June 13',
    byline: 'By Our Social Correspondent',
    body: 'General William Booth, the founder and commander of the Salvation Army, yesterday dedicated a new barracks in Commercial Street, Whitechapel, which is to serve as the principal centre of the Army\'s operations in the East End of London. The building, which cost eight thousand pounds, includes a chapel, a soup kitchen, a labour bureau, and dormitories for two hundred homeless men.\n\nIn his dedicatory address, General Booth renewed his call for the organised emigration of the London poor to the colonies, arguing that the overcrowded condition of the East End made gainful employment impossible for thousands.',
    category: 'domestic',
    columnSpan: 1,
  },
  // === THE COLONIES (5) ===
  {
    id: 'tc-1',
    headline: 'Indian Famine Relief Efforts Extended',
    subheadline: 'Viceroy Lord Curzon announces additional measures for Bombay Presidency',
    dateline: 'From our Special Correspondent, Calcutta, June 10',
    byline: 'By Our India Correspondent',
    body: 'The failure of the monsoon in the Deccan has brought famine conditions to an area inhabited by some three million souls. Lord Curzon, the Viceroy, has announced the extension of relief operations throughout the affected districts of the Bombay Presidency, with forty new relief works established.\n\nThe famine, the most severe since the great catastrophe of 1896-97, has already caused considerable mortality among the labouring classes. The Viceroy has cabled to the India Office in London requesting additional funds, and charitable subscriptions are being raised throughout Britain and the Empire.',
    image: 'engraving-colonies-01.jpg',
    caption: 'A relief camp in the Bombay Presidency',
    category: 'colonies',
    columnSpan: 2,
  },
  {
    id: 'tc-2',
    headline: 'Australian Commonwealth Bill Proclaimed',
    subheadline: 'Queen signs instrument uniting the six colonies',
    dateline: 'From our Correspondent, Melbourne, June 12',
    byline: 'By Our Australian Correspondent',
    body: 'The Commonwealth of Australia Constitution Act received the Royal Assent yesterday, and proclamations were read in the principal towns of all six Australian colonies. On the first day of January next, the colonies of New South Wales, Victoria, Queensland, South Australia, Western Australia, and Tasmania shall be united in a federal Commonwealth under the Crown.\n\nThe Earl of Hopetoun, the Governor-General designate, is expected to arrive at Sydney in December to make preparations for the inauguration. Lord Tennyson, the present Governor of South Australia, has been mentioned as a possible first Prime Minister.',
    category: 'colonies',
    columnSpan: 1,
  },
  {
    id: 'tc-3',
    headline: 'Canadian Pacific Railway Declares Dividend',
    subheadline: 'Record profits from western grain traffic',
    dateline: 'From our Correspondent, Montreal, June 11',
    byline: 'By Our Canadian Correspondent',
    body: 'The Canadian Pacific Railway Company has declared its half-yearly dividend of five per cent, a reflection of the extraordinary growth in western grain traffic. The new prairie settlements in Manitoba and the North-West Territories have produced a wheat harvest that has exceeded all expectations, and the CPR is transporting record quantities to the elevators at Fort William.\n\nSir William Van Horne, the President, has announced plans for the extension of the main line to the Pacific coast of British Columbia, with surveys now in progress for the Crow\'s Nest Pass line.',
    image: 'engraving-colonies-02.jpg',
    caption: 'A wheat field in Manitoba, the garden of the Empire',
    category: 'colonies',
    columnSpan: 1,
  },
  {
    id: 'tc-4',
    headline: 'South African Mines Resume Full Production',
    subheadline: 'Gold output returns to pre-war levels on the Rand',
    dateline: 'From our Correspondent, Johannesburg, June 9',
    byline: 'By Our South African Correspondent',
    body: 'The gold mines of the Witwatersrand have resumed full production for the first time since the conclusion of hostilities, with weekly output now exceeding the levels of 1899. Some forty thousand native labourers are now at work in the mines, and the recruitment of additional workers from Mozambique and the Transkei is proceeding satisfactorily.\n\nSir Alfred Milner, the High Commissioner, has expressed his satisfaction with the rapid recovery of the mining industry, which provides the principal revenue of the Transvaal Crown Colony. New deep-level workings are being established at the Village Main Reef and the Geldenhuis Estate.',
    category: 'colonies',
    columnSpan: 1,
  },
  {
    id: 'tc-5',
    headline: 'New Zealand Elects Liberal Government',
    subheadline: 'Mr. Seddon returned with increased majority',
    dateline: 'From our Correspondent, Wellington, June 8',
    byline: 'By Our New Zealand Correspondent',
    body: 'The general election in New Zealand has returned Mr. Richard Seddon\'s Liberal Government with an increased majority, confirming the Premier\'s extraordinary personal popularity. The Liberals have secured fifty of the eighty seats in the House of Representatives, with the Opposition Conservatives reduced to a rump of fifteen.\n\nMr. Seddon campaigned vigorously on his record of social reform, including old-age pensions, female suffrage, and industrial arbitration. The Premier has announced his intention to press for preferential trade arrangements with the United Kingdom.',
    category: 'colonies',
    columnSpan: 1,
  },
  // === COMMERCE & TRADE (5) ===
  {
    id: 'cm-1',
    headline: 'Bank Rate Unchanged at Three Per Cent',
    subheadline: 'City expresses confidence in monetary stability',
    dateline: 'From our City Correspondent, Threadneedle Street, June 14',
    byline: 'By Our City Editor',
    body: 'The Governor and Company of the Bank of England have announced that the minimum rate of discount will remain at three per cent for the current week. The decision, which was widely anticipated in the City, reflects the comfortable state of the money market and the absence of any unusual demand for accommodation.\n\nThe Governor, Mr. Albert George Sandeman, indicated to the Chancellor that the Bank\'s reserve stood at £18,450,000, a figure that gives ample margin for all legitimate demands. Consols were steady at 97 1/2, and colonial securities showed a firm tone throughout the day\'s business.',
    image: 'engraving-commerce-01.jpg',
    caption: 'The Bank of England, guardian of the nation\'s finances',
    category: 'commerce',
    columnSpan: 2,
  },
  {
    id: 'cm-2',
    headline: 'Shipping Intelligence: Atlantic Trade',
    subheadline: 'Cunard announces new express service to New York',
    dateline: 'From our Shipping Correspondent, Liverpool, June 13',
    byline: 'By Our Shipping Editor',
    body: 'The Cunard Steamship Company has announced the inauguration of a weekly express service between Liverpool and New York, to commence in September next. The new service will employ four turbine-powered vessels of twelve thousand tons, capable of maintaining an average speed of twenty-two knots.\n\nThe magnificent new express liner RMS Umbria, now nearing completion on the Clyde, will lead the service. The directors confidently predict that the crossing time will be reduced to five days and eighteen hours, establishing a new record for the Atlantic passage.',
    image: 'engraving-commerce-02.jpg',
    caption: 'The new Cunard express liner RMS Umbria on the Clyde',
    category: 'commerce',
    columnSpan: 1,
  },
  {
    id: 'cm-3',
    headline: 'Telephone Company Issues New Shares',
    subheadline: 'National Telephone Company capital increased to five million pounds',
    dateline: 'From our Correspondent, London, June 12',
    byline: 'By Our Financial Editor',
    body: 'The National Telephone Company has issued a prospectus for a further issue of two million pounds of ordinary shares, bringing the total capital of the company to five million. The new capital is required for the extension of the telephone network to some four hundred additional towns and villages throughout the United Kingdom.\n\nThe company now operates some 140,000 telephones, and the demand for new connections continues to outstrip supply. The Postmaster-General has indicated his satisfaction with the working of the existing licence, and there is no present intention of municipal acquisition.',
    category: 'commerce',
    columnSpan: 1,
  },
  {
    id: 'cm-4',
    headline: 'Cotton Market Report',
    subheadline: 'Prices firm on reports of reduced American crop',
    dateline: 'From our Correspondent, Liverpool, June 11',
    byline: 'By Our Cotton Reporter',
    body: 'The Liverpool cotton market opened this morning with a firm tone, Middling Orleans being quoted at 4.15d per pound. Reports from the United States indicate that the cotton crop of 1901 will be considerably below the average, owing to unfavourable weather conditions in Georgia and Alabama during the planting season.\n\nSpeculators have been covering short positions, and spinners are buying freely for forward requirements. The Manchester spinners\' associations report that orders are well maintained, though the trade remains intensely competitive.',
    category: 'commerce',
    columnSpan: 1,
  },
  {
    id: 'cm-5',
    headline: 'Manchester Ship Canal Nears Completion',
    subheadline: 'The thirty-six-mile waterway to open in September',
    dateline: 'From our Correspondent, Manchester, June 10',
    byline: 'By Our Engineering Correspondent',
    body: 'The Manchester Ship Canal, that vast engineering undertaking which has transformed the commerce of South Lancashire, is now virtually complete, and it is expected that ocean-going vessels will enter the canal docks at Salford early in September.\n\nThe canal, which extends thirty-six miles from Eastham on the Mersey estuary to Manchester, has cost some fifteen million pounds and has employed an average of twelve thousand navvies during its seven years of construction. The Queen has graciously consented to perform the formal opening ceremony.',
    category: 'commerce',
    columnSpan: 1,
  },
  // === ARTS & LETTERS (5) ===
  {
    id: 'al-1',
    headline: 'Mr. Henry Irving in King Arthur',
    subheadline: 'Lyceum Theatre presents new poetic drama by Mr. J. Comyns Carr',
    dateline: 'From our Dramatic Critic, London, June 13',
    byline: 'By Our Theatre Critic',
    body: 'Mr. Henry Irving last night added another triumph to his remarkable career with the first performance of "King Arthur," a new poetic drama by Mr. J. Comyns Carr, at the Lyceum Theatre. The production, which has been in preparation for several months, displayed all the legendary splendour of the Lyceum management.\n\nMr. Irving himself played the title role with that combination of nobility and pathos which has made him the foremost tragedian of his age. Miss Ellen Terry was a radiant Guinevere, and Mr. Forbes-Robertson distinguished himself as Sir Lancelot. The scenery, designed by Mr. Edward Burne-Jones, is of the most exquisite beauty.',
    image: 'engraving-arts-01.jpg',
    caption: 'Mr. Irving as King Arthur at the Lyceum Theatre',
    category: 'arts',
    columnSpan: 2,
  },
  {
    id: 'al-2',
    headline: 'Mr. Kipling\'s New Volume of Verse',
    subheadline: '"Kim" — a romance of India that enchants and enlightens',
    dateline: 'From our Literary Critic, London, June 12',
    byline: 'By Our Literary Editor',
    body: 'Mr. Rudyard Kipling has given the world a new masterpiece in "Kim," that remarkable romance of India which combines the colour and mystery of the East with a profound understanding of the Imperial mission. The novel, published this week by Macmillan, has already run to a second edition.\n\nThe story of the orphaned son of a British soldier, brought up as a native of Lahore, and his adventures with the lama Teshoo on the Great Road, is told with a wealth of detail and a depth of human sympathy that places it in the first rank of English fiction. The character of the lama is one of the great creations of modern literature.',
    image: 'engraving-arts-02.jpg',
    caption: 'Mr. Rudyard Kipling at his writing desk in Sussex',
    category: 'arts',
    columnSpan: 1,
  },
  {
    id: 'al-3',
    headline: 'Royal Academy Summer Exhibition',
    subheadline: 'The one hundred and thirty-third annual display opens at Burlington House',
    dateline: 'From our Art Critic, London, June 11',
    byline: 'By Our Art Critic',
    body: 'The Summer Exhibition of the Royal Academy opened to the public yesterday, and the galleries at Burlington House were thronged with visitors anxious to inspect the productions of the British School for 1901. The collection numbers some fifteen hundred works, and the general standard is remarkably high.\n\nMr. John Singer Sargent contributes a magnificent portrait of the Dowager Countess of Dalhousie, and Mr. Lawrence Alma-Tadema exhibits a classical scene of great refinement. Mr. John Everett Millais, whose untimely death last year was so grievous a loss to British art, is represented by a posthumous work.',
    category: 'arts',
    columnSpan: 1,
  },
  {
    id: 'al-4',
    headline: 'Madame Melba at Covent Garden',
    subheadline: 'Australian prima donna triumphs in La Traviata',
    dateline: 'From our Musical Critic, London, June 10',
    byline: 'By Our Music Critic',
    body: 'The Royal Opera at Covent Garden was filled to its utmost capacity last night for the first London performance of Verdi\'s "La Traviata" this season, with Madame Nellie Melba in the role of Violetta. The Australian prima donna has never been heard to greater advantage.\n\nHer rendering of the famous "Sempre libera" in the first act was a miracle of vocal virtuosity, and the pathos of the death scene in the third act moved the entire audience to tears. Signor Caruso, as Alfredo, partnered her with distinction.',
    category: 'arts',
    columnSpan: 1,
  },
  {
    id: 'al-5',
    headline: 'New Novel from Mrs. Humphry Ward',
    subheadline: '"Eleanor" — a study of contemporary society',
    dateline: 'From our Literary Critic, London, June 9',
    byline: 'By Our Literary Editor',
    body: 'Mrs. Humphry Ward has published a new novel, "Eleanor," which deals with the intellectual and spiritual problems of modern womanhood. The story, which is set partly in Oxford and partly in London, follows the career of a gifted young woman whose literary ambitions come into conflict with the claims of family and society.\n\nThe novel is certain to provoke considerable discussion, for Mrs. Ward treats the questions of female education and female suffrage with a freedom that many will find startling. The character of Eleanor herself is drawn with remarkable subtlety and depth.',
    category: 'arts',
    columnSpan: 1,
  },
  // === SCIENCE & INDUSTRY (5) ===
  {
    id: 'si-1',
    headline: 'Professor Röntgen\'s Rays at the Royal Society',
    subheadline: 'Demonstration of X-ray photography astounds learned fellows',
    dateline: 'From our Scientific Correspondent, Burlington House, June 13',
    byline: 'By Our Science Editor',
    body: 'The Royal Society was the scene yesterday of a demonstration that will long be remembered in the annals of science. Professor Silvanus Thompson, acting on behalf of Professor Wilhelm Röntgen of Würzburg, exhibited the remarkable rays which penetrate solid matter and reveal the hidden structure of the human body.\n\nA volunteer from the audience was subjected to the rays, and the assembled Fellows were astonished to see the bones of the hand and wrist displayed upon a fluorescent screen as clearly as if the flesh had been removed. Medical men present declared that this discovery must revolutionise the practice of surgery.',
    image: 'engraving-science-01.jpg',
    caption: 'Professor Thompson demonstrating the Röntgen rays at Burlington House',
    category: 'science',
    columnSpan: 2,
  },
  {
    id: 'si-2',
    headline: 'First Transatlantic Wireless Signals',
    subheadline: 'Mr. Marconi achieves communication across the ocean',
    dateline: 'From our Correspondent, St. John\'s, Newfoundland, June 12',
    byline: 'By Our Scientific Correspondent',
    body: 'Mr. Guglielmo Marconi has succeeded in transmitting wireless telegraphic signals across the Atlantic Ocean, a feat which scientific authorities had declared impossible. The signals, comprising the Morse letter "S" (three dots), were received at Signal Hill, St. John\'s, Newfoundland, from the station at Poldhu in Cornwall, a distance of some two thousand miles.\n\nMr. Marconi has been engaged upon this experiment for several months, and his success promises to revolutionise ocean communication. The Post Office and the Admiralty have both expressed keen interest in the practical applications of the invention.',
    category: 'science',
    columnSpan: 1,
  },
  {
    id: 'si-3',
    headline: 'Glasgow International Exhibition Opened',
    subheadline: 'Lord Kelvin inaugurates great display of arts and manufactures',
    dateline: 'From our Correspondent, Glasgow, June 11',
    byline: 'By Our Scottish Correspondent',
    body: 'The Glasgow International Exhibition of 1901 was formally opened by Lord Kelvin in the presence of a vast concourse of spectators. The exhibition, which occupies the extensive grounds at Kelvingrove Park, is devoted to the display of arts, manufactures, and scientific appliances from all parts of the British Empire and foreign countries.\n\nLord Kelvin, in his inaugural address, dwelt upon the remarkable progress of science and industry during the reign of Her Majesty, and expressed his conviction that the twentieth century would witness even more startling advances. The exhibition is expected to attract some three million visitors.',
    image: 'engraving-science-02.jpg',
    caption: 'The magnificent Palace of Industries at Kelvingrove Park',
    category: 'science',
    columnSpan: 1,
  },
  {
    id: 'si-4',
    headline: 'Ordnance Survey Completes New Maps',
    subheadline: 'One-inch survey of England and Wales finished after twenty years',
    dateline: 'From our Correspondent, Southampton, June 10',
    byline: 'By Our Survey Correspondent',
    body: 'The Ordnance Survey Office at Southampton has announced the completion of the revised one-inch map of England and Wales, a work which has occupied the staff of the Survey for more than twenty years. The new maps incorporate all the changes in boundaries, roads, and buildings that have occurred since the previous survey of 1870-90.\n\nColonel Charles Close, the Director-General, has presented a complete set of the three hundred and sixty sheets to the British Museum. The maps are available to the public at two shillings per sheet, and a popular edition in folding form is in preparation.',
    category: 'science',
    columnSpan: 1,
  },
  {
    id: 'si-5',
    headline: 'New Steam Turbine for Naval Vessels',
    subheadline: 'Mr. Charles Parsons demonstrates revolutionary engine',
    dateline: 'From our Naval Correspondent, Newcastle, June 9',
    byline: 'By Our Engineering Editor',
    body: 'Mr. Charles Parsons has demonstrated to the Admiralty a new steam turbine engine of such extraordinary power and compactness that it promises to revolutionise naval propulsion. The engine, which has been installed in the torpedo-boat destroyer HMS Viper, has driven the vessel at the unprecedented speed of thirty-six knots.\n\nThe Admiralty has placed orders for further turbine-powered destroyers, and there is talk of installing turbines in the next class of battleships. Mr. Parsons\'s invention represents the most significant advance in marine engineering since the introduction of the screw propeller.',
    category: 'science',
    columnSpan: 1,
  },
  // === SOCIETY & FASHION (5) ===
  {
    id: 'sf-1',
    headline: 'Court Circular: Drawing Room at Buckingham Palace',
    subheadline: 'Their Royal Highnesses receive the nobility in afternoon presentation',
    dateline: 'From our Court Correspondent, Buckingham Palace, June 14',
    byline: 'By Our Society Editor',
    body: 'Her Royal Highness the Princess of Wales held a Drawing Room at Buckingham Palace yesterday afternoon for the presentation of ladies to the Court. Their Royal Highnesses the Duke and Duchess of York were in attendance, and the suite of state rooms presented a scene of brilliant animation.\n\nSome four hundred ladies were presented, including the Countess of Derby, the Marchioness of Londonderry, and Lady Randolph Churchill. The costumes were of the most elaborate description, with Court trains of velvet and satin being much in evidence. The Queen\'s colour of mauve was displayed in numerous toilettes.',
    image: 'engraving-society-01.jpg',
    caption: 'The Grand Reception Room at Buckingham Palace',
    category: 'society',
    columnSpan: 2,
  },
  {
    id: 'sf-2',
    headline: 'Marriage of Lord Rosebery\'s Daughter',
    subheadline: 'Lady Sybil Primrose weds Captain Charles Balfour',
    dateline: 'From our Correspondent, The Durdans, Epsom, June 13',
    byline: 'By Our Society Editor',
    body: 'The marriage of Lady Sybil Primrose, youngest daughter of the Earl of Rosebery, to Captain the Hon. Charles Balfour, second son of Lord Balfour of Burleigh, was celebrated yesterday at St. Mary\'s Church, Epsom, in the presence of a large and distinguished congregation.\n\nThe bride, who was given away by her father, wore a gown of white satin trimmed with Brussels lace, and carried a bouquet of white orchids. Her eight bridesmaids were attired in pink chiffon over white satin. The Prince of Wales was among the many notable guests at the reception at The Durdans.',
    category: 'society',
    columnSpan: 1,
  },
  {
    id: 'sf-3',
    headline: 'Ascot Race Meeting: Gold Cup Day',
    subheadline: 'Mr. Leopold de Rothschild\'s colt carries the blue riband',
    dateline: 'From our Turf Correspondent, Ascot, June 12',
    byline: 'By Our Turf Editor',
    body: 'The Royal Ascot meeting reached its climax yesterday with the running of the Gold Cup for three-year-olds and upwards. The race, which attracted an immense attendance including the Prince and Princess of Wales, was won in most impressive fashion by Mr. Leopold de Rothschild\'s five-year-old colt, Jimnast.\n\nThe royal party occupied the traditional stand, and the Princess of Wales created a sensation with a costume of lilac chiffon and a hat of immense proportions trimmed with ospreys. The King of Portugal, who is visiting England, was a guest in the royal enclosure.',
    image: 'engraving-society-02.jpg',
    caption: 'The Gold Cup procession on the third day of the Ascot meeting',
    category: 'society',
    columnSpan: 1,
  },
  {
    id: 'sf-4',
    headline: 'The Season at Cowes Regatta',
    subheadline: 'Royal Yacht Squadron entertains in splendid style',
    dateline: 'From our Yachting Correspondent, Cowes, June 11',
    byline: 'By Our Yachting Editor',
    body: 'The annual regatta of the Royal Yacht Squadron opened at Cowes yesterday under the most favourable conditions of wind and weather. The Solent was dotted with the white sails of competing yachts, and the esplanade presented a brilliant scene as the fashionable world assembled to witness the sport.\n\nHis Majesty the King of Portugal, who is staying at Osborne as the guest of the Prince and Princess of Wales, witnessed the racing from the royal yacht Alberta. The Britannia, the Prince of Wales\'s famous cutter, carried away the Queen\'s Cup with a display of sailing that excited universal admiration.',
    category: 'society',
    columnSpan: 1,
  },
  {
    id: 'sf-5',
    headline: 'Fashions for the Summer Season',
    subheadline: 'The new silhouettes from Paris and London couturiers',
    dateline: 'From our Fashion Correspondent, London, June 10',
    byline: 'By Our Fashion Editor',
    body: 'The leading couturiers of Paris and London have now completed their collections for the summer season of 1901, and the fashionable world is adopting the new silhouettes with characteristic enthusiasm. The most notable feature of the season is the continuing popularity of the S-bend corset, which produces the distinctive "monobosom" effect so favoured by the younger set.\n\nFor evening wear, the directoire style remains in vogue, with high waists and trained skirts of chiffon and mousseline de soie. The new colour of "eau de Nil" has made a considerable sensation, and is to be seen in every drawing room and at every theatre.',
    category: 'society',
    columnSpan: 1,
  },
  // === CLASSIFIEDS (5) ===
  {
    id: 'cl-1',
    headline: 'BOVRIL — The Great Strength Giver',
    subheadline: 'Nurtures the weak, sustains the strong',
    dateline: 'Advertisement',
    byline: 'Bovril Ltd., London',
    body: 'Bovril is the concentrated essence of finest beef, prepared by a patented process that preserves all the nourishing properties of the meat. It is invaluable for invalids, convalescents, and athletes. A cup of hot Bovril is the finest restorative known to medical science.\n\nSold by all grocers and chemists. Price 1/-, 2/6, and 5/-. Ask your dealer for the genuine article in the distinctive jar.',
    image: 'ad-bovril.jpg',
    caption: 'Bovril Ltd., 142 Old Street, London, E.C.',
    category: 'classifieds',
    columnSpan: 1,
  },
  {
    id: 'cl-2',
    headline: 'PEAR\'S SOAP — For the Complexion',
    subheadline: 'Matchless for the skin — used by the Royal Family',
    dateline: 'Advertisement',
    byline: 'A. & F. Pears Ltd., London',
    body: 'Pears\' Soap is the perfection of personal cleanliness. Its purity and emollient properties render it invaluable for the preservation of a clear complexion. Used and recommended by Her Majesty the Queen and the Royal Princesses.\n\nSold everywhere. A large tablet, 6d. A trial will convince you of its superior merits.',
    image: 'ad-pears-soap.jpg',
    caption: 'Pears\' Soap — the perfection of purity',
    category: 'classifieds',
    columnSpan: 1,
  },
  {
    id: 'cl-3',
    headline: 'Visit the West Country — Great Western Railway',
    subheadline: 'The most beautiful scenery in England',
    dateline: 'Advertisement',
    byline: 'Great Western Railway Company, Paddington Station',
    body: 'The Great Western Railway offers the fastest and most comfortable service to Devon, Cornwall, Somerset, and the South-West. Express trains leave Paddington every hour. First-class carriages are fitted with electric light and heating.\n\nIllustrated guidebooks available at all stations. Enquire at the Superintendent of the Line, Paddington Station, W.',
    image: 'ad-railway.jpg',
    caption: 'The Cornish Riviera Express — the most scenic journey in Britain',
    category: 'classifieds',
    columnSpan: 1,
  },
  {
    id: 'cl-4',
    headline: 'The Perfect Form Corset',
    subheadline: 'Ladies\' exquisite fittings — unrivalled shape',
    dateline: 'Advertisement',
    byline: 'The Perfect Form Corset Co., Regent Street',
    body: 'The Perfect Form Corset combines elegance with comfort, giving the fashionable silhouette without the slightest constraint. Made from the finest coutil, with whalebone of the best quality. Available in all sizes and in white, drab, or black.\n\nPrice from 4/11 to 21/-. Sent post free on receipt of remittance. Showrooms at 145 Regent Street, London, W.',
    image: 'ad-corsets.jpg',
    caption: 'The Perfect Form — for the refined silhouette',
    category: 'classifieds',
    columnSpan: 1,
  },
  {
    id: 'cl-5',
    headline: 'Dr. Percival\'s Vegetable Life Tonic',
    subheadline: 'Restores vitality, renews the blood',
    dateline: 'Advertisement',
    byline: 'Percival & Co., Apothecaries, London',
    body: 'For weakness, fatigue, and lack of vigour, Dr. Percival\'s celebrated Vegetable Tonic is the certain remedy. Prepared from the choicest roots and herbs by an entirely vegetable process.\n\nA sure cure for all nervous diseases, debility, and low spirits. Price 2/6 and 4/6 per bottle. Sold by all chemists, or sent post free.',
    image: 'ad-tonic.jpg',
    caption: 'Dr. Percival\'s — the great restorative',
    category: 'classifieds',
    columnSpan: 1,
  },
  // === SPORTS (5) ===
  {
    id: 'sp-1',
    headline: 'The Gentlemen v. Players at Lord\'s',
    subheadline: 'A magnificent century by Mr. C.B. Fry captivates the spectators',
    dateline: 'From our Cricket Correspondent, Lord\'s, June 14',
    byline: 'By Our Cricket Editor',
    body: 'The annual match between the Gentlemen and the Players at Lord\'s Cricket Ground produced one of the most brilliant displays of batting seen in recent years. Mr. C.B. Fry, the Oxford University and Sussex amateur, scored a magnificent century, finishing with 138 not out, an innings that included three sixes and seventeen fours.\n\nThe Players, in their first innings, had made a respectable 246, thanks chiefly to a patient 89 by Mr. George Hirst. The Gentlemen, in reply, were in some trouble at 87 for four when Mr. Fry was joined by Mr. Ranjitsinhji, and the two batsmen put on 186 runs in under two hours.',
    image: 'engraving-sports-01.jpg',
    caption: 'Mr. Fry driving to the boundary during his magnificent innings',
    category: 'sports',
    columnSpan: 2,
  },
  {
    id: 'sp-2',
    headline: 'Derby Day: Volodyovski Wins the Blue Riband',
    subheadline: 'Mr. W. C. Whitney\'s colt carries the colours to victory',
    dateline: 'From our Turf Correspondent, Epsom, June 12',
    byline: 'By Our Racing Editor',
    body: 'The one hundred and twenty-first running of the Derby Stakes was won yesterday by Mr. W. C. Whitney\'s Volodyovski, a three-year-old bay colt by Florizel II out of Voluta. The race was run before the customary immense concourse, and the state of the going was good to firm.\n\nVolodyovski, trained by Mr. J. Huggins at Newmarket and ridden by the American jockey, Mr. Lester Reiff, started at 5-to-1 and won by three-quarters of a length from Mr. Leopold de Rothschild\'s Doricles. The favourite, Handicapper, finished a disappointing fourth.',
    image: 'engraving-sports-02.jpg',
    caption: 'The finish of the Derby — Volodyovski (centre) beats Doricles',
    category: 'sports',
    columnSpan: 1,
  },
  {
    id: 'sp-3',
    headline: 'Oxford Win the University Boat Race',
    subheadline: 'Dark Blues defeat Cambridge by two lengths at Putney',
    dateline: 'From our Rowing Correspondent, Putney, June 10',
    byline: 'By Our aquatic Editor',
    body: 'The fifty-eighth annual contest between the crews of Oxford and Cambridge Universities was rowed yesterday over the championship course from Putney to Mortlake, and resulted in a well-merited victory for Oxford by two lengths. The Dark Blues won the toss and chose the Surrey station.\n\nThe race was rowed in fine weather, with a moderate following wind. Oxford led from the start and gradually increased their advantage, passing Hammersmith Bridge with a clear water lead. The winning time of 19 minutes 45 seconds was remarkably fast for the conditions.',
    category: 'sports',
    columnSpan: 1,
  },
  {
    id: 'sp-4',
    headline: 'Wimbledon Championships: First Round',
    subheadline: 'Mr. Doherty and Miss Cooper advance in convincing fashion',
    dateline: 'From our Lawn Tennis Correspondent, Wimbledon, June 11',
    byline: 'By Our Lawn Tennis Editor',
    body: 'The All England Lawn Tennis Championships opened at Wimbledon yesterday with the first round of the gentlemen\'s and ladies\' singles. Mr. Laurence Doherty, the defending champion and overwhelming favourite, advanced with contemptuous ease, defeating Mr. G. Ball-Greene in straight sets.\n\nIn the ladies\' event, Miss Charlotte Cooper, the champion of 1895 and 1896, signalled her intention to regain the title by overwhelming her first-round opponent without conceding a game. The attendance was the largest ever recorded for the opening day.',
    category: 'sports',
    columnSpan: 1,
  },
  {
    id: 'sp-5',
    headline: 'International Rugby: England Defeat Scotland',
    subheadline: 'Four tries to one at Richmond Athletic Ground',
    dateline: 'From our Rugby Correspondent, Richmond, June 9',
    byline: 'By Our Rugby Editor',
    body: 'The annual rugby football match between England and Scotland was played yesterday at the Richmond Athletic Ground before a crowd of some fifteen thousand spectators, and resulted in a decisive victory for England by four tries and a penalty goal to one try.\n\nThe English forwards, who were markedly superior in the scrummage, provided their three-quarters with an abundance of good ball, and the scoring was begun in the first five minutes when Mr. J. E. Raphael touched down between the posts. Scotland rallied briefly in the second half, but England\'s defence was never seriously threatened.',
    category: 'sports',
    columnSpan: 1,
  },
];

export const useContentStore = create<ContentState>(() => ({
  articles,
  getArticlesByCategory: (category: string) =>
    articles.filter((a) => a.category === category),
  getArticleById: (id: string) =>
    articles.find((a) => a.id === id),
}));
